export const categories = [
  { id: 0, name: "All" },
  { id: 1, name: "Tropical" },
  { id: 2, name: "Subtropical" },
  { id: 3, name: "Desert" },
  { id: 4, name: "Temperate" },
  { id: 5, name: "Mediterranean" },
  { id: 6, name: "Worldwide (Cosmopolitan)" },
];
export const favouriteList = [];
export const plants = [
  {
    id: "e4ud",
    name: "Snake Plant",
    categoryId: "1",
    size: "medium",
    plant: "Sansevieria trifasciata",
    data: "The Snake Plant, also known as Mother-in-Law’s Tongue, is a resilient tropical plant native to West Africa. It features upright, sword-like leaves with dark green bands and lighter horizontal stripes, making it a visually striking addition to any indoor space. Known for its exceptional air-purifying abilities, it filters toxins such as formaldehyde and benzene. This plant thrives in low light and requires minimal watering, making it ideal for beginners or busy lifestyles. Its drought-tolerant nature and resistance to pests make it one of the easiest and most rewarding houseplants to grow, even in offices and bedrooms.",
    height: 45,
    image: [
      "https://plantsome.com/cdn/shop/files/Laurentii4in_1e9d65a8-68d6-4d45-87b2-b9057444c410.png?v=1731027908&width=630",
      "https://plantsome.com/cdn/shop/files/ZeylanicaSnake4in.png?v=1731029421&width=630",
    ],
    humidity: 40,
    price: 24.99,
  },
  {
    id: "iykn",
    name: "Sansevieria 'Samurai Dwarf'",
    categoryId: "1",
    size: "small",
    plant: "Dracaena hanningtonii",
    data: "Sansevieria 'Samurai Dwarf' is a compact and unique succulent with an eye-catching rosette formation of thick, short, dark green leaves edged with white or reddish margins. It grows slowly and reaches a height of only 15-30 cm, making it perfect for desktops or small spaces. Despite its size, it has all the hardy characteristics of larger snake plants—tolerating low light, infrequent watering, and dry indoor air. This cultivar is ideal for minimalistic or modern interiors and requires almost no maintenance. Its architectural shape and compact growth habit make it both ornamental and functional in improving indoor air quality.",
    height: 30,
    image: [
      "https://plantsguru.com/cdn/shop/files/Sansevieria-samurai-dwarf.jpg",
    ],
    humidity: 35,
    price: 19.99,
  },
  {
    id: "4es1",
    name: "Spider Plant",
    categoryId: "4",
    size: "medium",
    plant: "Chlorophytum comosum",
    data: "The Spider Plant is one of the most popular and easy-to-grow indoor plants, cherished for its long arching leaves that are green with white or yellow stripes. Native to South Africa, this hardy plant is known for producing offshoots or 'babies' that dangle down like spiders on a web. It thrives in indirect light and well-draining soil, requiring moderate watering. Not only is it visually appealing, but it also helps clean indoor air by removing pollutants. Perfect for hanging baskets or elevated shelves, the Spider Plant adds a touch of nature to any room while being safe for pets.",
    height: 35,
    image: [
      "https://s.alicdn.com/@sc04/kf/H2685a841eeaa49efba36941a3c28fd2bW.jpg_720x720q50.jpg",
    ],
    humidity: 50,
    price: 15.99,
  },
  {
    id: "qh2k",
    name: "Aloe Vera",
    categoryId: "3",
    size: "small",
    plant: "Aloe barbadensis",
    data: "Aloe Vera is a succulent plant best known for its medicinal and skincare benefits. Its thick, fleshy leaves contain a soothing gel that can be applied to burns, cuts, and skin irritations. This drought-tolerant plant thrives in bright, indirect sunlight and requires very little water, making it perfect for beginners or those with busy lifestyles. Native to arid climates, Aloe Vera is a resilient houseplant that purifies the air and adds a fresh green touch to interiors. It prefers well-draining soil and should be allowed to dry out completely between waterings. It's an essential addition to any wellness-focused home.",
    height: 25,
    image: [
      "https://images.pexels.com/photos/10718303/pexels-photo-10718303.jpeg",
    ],
    humidity: 30,
    price: 12.99,
  },
  {
    id: "j58d",
    name: "Money Plant",
    categoryId: "1",
    size: "medium",
    plant: "Epipremnum aureum",
    data: "The Money Plant, often associated with good luck and prosperity, is a vigorous climber featuring heart-shaped green leaves that can develop golden or white variegation. Highly adaptable, it thrives in a wide range of lighting conditions, from low light to bright indirect sun. It’s commonly grown in hanging baskets, water vases, or trained to climb poles. Aside from its aesthetic appeal, it’s also an excellent air purifier, removing toxins like benzene and xylene. Low maintenance and fast-growing, the Money Plant is perfect for both homes and offices. It can even grow in water alone, making it highly versatile.",
    height: 40,
    image: [
      "https://images.othoba.com/images/thumbs/0802324_money-plant-14-inch-long-plants-for-home-and-office-decoration.jpeg",
    ],
    humidity: 45,
    price: 14.99,
  },
  {
    id: "f7qe",
    name: "Dracaena Robusta Dwarf",
    categoryId: "1",
    size: "medium",
    plant: "Dracaena sp.",
    data: "Dracaena Robusta Dwarf is a compact variety of the larger Dracaena family, celebrated for its attractive foliage and hardiness. It features broad, upright leaves that are dark green with streaks of silvery grey or lighter green, giving it a textured, sculptural look. This low-maintenance plant is tolerant of low light and dry air, making it ideal for indoor spaces like offices, bedrooms, or living rooms. It prefers to dry out between waterings and thrives in well-draining soil. Known for purifying air pollutants like xylene and formaldehyde, it combines functionality and beauty in a neat, compact plant form.",
    height: 40,
    image: [
      "https://img.freepik.com/premium-psd/dracaena-trifasciata-plant-psd-white-background_889056-95469.jpg",
    ],
    humidity: 40,
    price: 22.99,
  },
  {
    id: "3emc",
    name: "Areca Palm",
    categoryId: "1",
    size: "large",
    plant: "Dypsis lutescens",
    data: "The Areca Palm, also known as the Butterfly Palm, is a tropical beauty that brings a lush, exotic feel to any indoor or outdoor space. Its feathery, arching fronds consist of dozens of narrow leaflets, creating a dense and graceful canopy. Ideal for bright, indirect sunlight, it can grow quite tall and is often used to create natural privacy screens indoors. The Areca Palm is non-toxic to pets and known for its air-purifying abilities, removing harmful indoor pollutants. It enjoys moderate watering and higher humidity, making it a stunning choice for plant enthusiasts seeking a touch of the tropics.",
    height: 75,
    image: [
      "https://t3.ftcdn.net/jpg/14/82/04/08/360_F_1482040860_FhG7KhAmEhchlFnFG6JfY7eKSEd9AcGG.jpg",
    ],
    humidity: 55,
    price: 49.99,
  },
  {
    id: "dobi",
    name: "Zebra Plant Succulent",
    categoryId: "3",
    size: "small",
    plant: "Haworthiopsis attenuata",
    data: "The Zebra Plant Succulent is a compact and visually stunning plant known for its deep green leaves with horizontal white stripes that resemble a zebra’s pattern. Native to South Africa, this low-maintenance plant is perfect for beginners or small-space gardening. It prefers bright, indirect light and infrequent watering, thriving in dry indoor environments. The rosette-shaped growth makes it a great choice for decorative pots and tabletops. Unlike many succulents, it tolerates slightly lower light, making it adaptable to office or indoor settings. It adds texture and character to any plant collection without demanding much care or attention.",
    height: 20,
    image: [
      "https://t4.ftcdn.net/jpg/15/34/29/25/360_F_1534292517_RrjM8GYzGLnFwqwYpq4bEklaCOr4fMkI.jpg",
    ],
    humidity: 30,
    price: 18.99,
  },
  {
    id: "tn7b",
    name: "Philodendron",
    categoryId: "1",
    size: "medium",
    plant: "Philodendron hederaceum",
    data: "Philodendron is a classic tropical houseplant loved for its fast-growing, trailing vines and heart-shaped green leaves. It’s exceptionally easy to care for and thrives in medium to bright indirect light. Its trailing growth makes it ideal for hanging baskets or training along shelves and walls. Water it when the top inch of soil feels dry, and it will reward you with vigorous growth. The plant also helps purify indoor air and is tolerant of a range of conditions. With its elegant, lush foliage, the Philodendron adds a natural, calming vibe to any room, perfect for plant lovers at all levels.",
    height: 40,
    image: [
      "https://img.freepik.com/free-photo/monstera-deliciosa-plant-pot_53876-133119.jpg",
    ],
    humidity: 60,
    price: 22.99,
  },
  {
    id: "zh9j",
    name: "Rubber Plant",
    categoryId: "1",
    size: "large",
    plant: "Ficus elastica",
    data: "The Rubber Plant is a striking, upright houseplant with large, glossy, deep green leaves that can have a reddish or burgundy hue. Native to Southeast Asia, it can grow into a small indoor tree with the right care. It prefers bright indirect light and slightly moist soil, although it can tolerate lower light and occasional neglect. This plant makes a bold statement in any room and is highly effective at purifying indoor air. Over time, it can be pruned to maintain a compact size or allowed to grow tall. A favorite among interior designers, it's both functional and dramatic.",
    height: 70,
    image: [
      "https://img.freepik.com/premium-photo/indoor-potted-rubber-plant-white-background-easy-remove-backgroun_1308044-35.jpg",
    ],
    humidity: 50,
    price: 39.99,
  },
  {
    id: "h4h6",
    name: "Pothos",
    categoryId: "1",
    size: "medium",
    plant: "Epipremnum aureum",
    data: "Pothos is one of the easiest houseplants to grow, making it ideal for beginners and experienced gardeners alike. Its heart-shaped leaves come in a variety of colors and patterns, such as golden, marble, or neon green. This vining plant thrives in a range of lighting conditions, from low to bright indirect light, and can be grown in soil or water. It’s extremely forgiving if neglected and only needs occasional watering. Pothos is also known for filtering indoor air pollutants. It’s perfect for hanging baskets, window sills, or trailing down from shelves, adding beauty and greenery with little effort.",
    height: 35,
    image: [
      "https://s.alicdn.com/@sc04/kf/H760f1a7758014cb286a37ab305a40ec8v.jpg_720x720q50.jpg",
    ],
    humidity: 45,
    price: 12.99,
  },
];

export const cartData: { id: string; plantId: string; quantity: number }[] = [];
